# Generated by Django 3.1.5 on 2021-10-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Dúvida frequente',
                'verbose_name_plural': 'Dúvidas frequentes',
            },
        ),
        migrations.AlterModelOptions(
            name='ator',
            options={'verbose_name': 'Ator', 'verbose_name_plural': 'Atores'},
        ),
        migrations.AlterModelOptions(
            name='filme',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.AlterField(
            model_name='ator',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='atores',
            field=models.ManyToManyField(to='todo.Ator', verbose_name='Atores'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.IntegerField(verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.CharField(max_length=100, verbose_name='Sinopse'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidade',
            field=models.IntegerField(verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.filme', verbose_name='Filme'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.sala', verbose_name='Sala'),
        ),
    ]
