# Generated by Django 3.1.5 on 2021-11-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.cidade', verbose_name='Cidade'),
        ),
    ]
