# Generated by Django 3.1.5 on 2021-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_usuario_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='fotoCapa',
            field=models.ImageField(null=True, upload_to=None, width_field=1024),
        ),
    ]
