# Generated by Django 3.1.5 on 2021-11-22 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_filme_fotocapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário logado'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='fotoCapa',
            field=models.ImageField(max_length=255, null=True, upload_to='filmes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefone'),
        ),
    ]
