# Generated by Django 3.1.5 on 2022-05-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20211122_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='descricao',
            field=models.CharField(max_length=100, null=True, verbose_name='Descricao'),
        ),
    ]
