# Generated by Django 3.1.5 on 2022-06-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20220530_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='urlPagamento',
            field=models.CharField(max_length=255, null=True, verbose_name='URL Pagamento'),
        ),
    ]
