# Generated by Django 3.1.5 on 2022-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_pedido_urlpagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
